import type { BufferGeometry } from 'three';

/**
 * Converts a Three.js BufferGeometry to a binary STL Blob
 * and triggers a browser download.
 */
export function downloadSTL(geometry: BufferGeometry, filename = 'model.stl'): void {
  const blob = geometryToSTLBlob(geometry);
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function geometryToSTLBlob(geometry: BufferGeometry): Blob {
  const posAttr = geometry.getAttribute('position');
  const normalAttr = geometry.getAttribute('normal');
  const index = geometry.getIndex();

  const triangleCount = index ? index.count / 3 : posAttr.count / 3;
  const buffer = new ArrayBuffer(84 + triangleCount * 50);
  const view = new DataView(buffer);

  // 80-byte ASCII header
  const header = 'Generated by Artificialis — https://github.com/marquesgabriel/artificialis.github.io';
  for (let i = 0; i < 80; i++) {
    view.setUint8(i, i < header.length ? header.charCodeAt(i) : 0);
  }
  view.setUint32(80, triangleCount, true);

  let offset = 84;

  const getV = (i: number) => ({
    x: posAttr.getX(i), y: posAttr.getY(i), z: posAttr.getZ(i),
  });
  const getN = (i: number) => ({
    x: normalAttr.getX(i), y: normalAttr.getY(i), z: normalAttr.getZ(i),
  });

  for (let t = 0; t < triangleCount; t++) {
    const i0 = index ? index.getX(t * 3)     : t * 3;
    const i1 = index ? index.getX(t * 3 + 1) : t * 3 + 1;
    const i2 = index ? index.getX(t * 3 + 2) : t * 3 + 2;

    const n = getN(i0);
    view.setFloat32(offset, n.x, true); offset += 4;
    view.setFloat32(offset, n.y, true); offset += 4;
    view.setFloat32(offset, n.z, true); offset += 4;

    for (const idx of [i0, i1, i2]) {
      const v = getV(idx);
      view.setFloat32(offset, v.x, true); offset += 4;
      view.setFloat32(offset, v.y, true); offset += 4;
      view.setFloat32(offset, v.z, true); offset += 4;
    }

    view.setUint16(offset, 0, true); offset += 2;
  }

  return new Blob([buffer], { type: 'application/octet-stream' });
}